### ISSUE TITLE
Role delegation permissions are being saved in user.role.[ROLE].json, but role delegation per user does not work

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-contrib/role_delegation#1]
In the current code, the role delegation is being saved to (or deleted from) the database in `role_delegation_form_user_admin_role_submit()` and in `role_delegation_user_role_delete())`. 

This does not have any effect on the user, however. When selecting a user's role(s), they do not save to the database and/or are not fetched from the database. 

Need to figure out where this should be writing to/fetching from in the database and correct this in the code.

**Comment by klonos** [comment]
Hello @kelizoliva 👋 ...I have responded to #2 and believe that the cause of this is the same as what I have described there, re https://api.backdropcms.org/change-records/user-entity-now-classed-object 😉

**Comment by klonos** [comment]
...I would try to change the `backdrop_drupal_compatibility` setting in your `settings.php` to `FALSE`, and also enable all errors in `admin/config/development/logging` if not done already. Then perhaps checking the log in `admin/reports/dblog` would show you something helpful 😉

**Comment by kelizoliva** [comment]
Resolved by #5
