### ISSUE TITLE
Role delegation saved to user.role.[ROLE].json file(s), but not by the module

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-contrib/role_delegation#2]
Role delegation is somehow also being saved to the user.role.[ROLE].json file(s), though nothing in the module is writing to the json files. Curious about what is going on here.

**Comment by klonos** [comment]
Not 100% sure, but it seems that [`user_save()`](https://api.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_save/1) in this line would be doing the saving to config files: https://github.com/kelizoliva/role_delegation/blob/1.x-1.x/role_delegation.module#L135

In your implementation, you seem to still be passing a second argument to that function, whereas in Backdrop, only the user object should be passed. This should be of help I believe: https://api.backdropcms.org/change-records/user-entity-now-classed-object

**Comment by klonos** [comment]
...also this: https://github.com/kelizoliva/role_delegation/blob/1.x-1.x/role_delegation.module#L236:

```php
function role_delegation_user_presave(&$edit, $account) {
```

...should really be:

```php
function role_delegation_user_presave($account) {
```

**Comment by klonos** [comment]
...there may be other places in code where changes may be needed. I have not checked thoroughly, but this info should give you something to get moving again 🙂

**Comment by kelizoliva** [comment]
Noted and attempted to remove &$edit from the role_delegation_user_presave() function, but I have a feeling there is still more work to be done in this function beyond that. Admittedly I am still stumbling over these user entity changes. I will review the user_save() function and try to figure this out. Thanks!

**Comment by kelizoliva** [comment]
This is working as designed, role delegations module is permissions based. Permissions are being correctly applied to user role config files.
