### ISSUE TITLE
Get it fully working

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/role_delegation#4]
I'm working on fixes for this to get it fully working, which I'll share.

**Comment by herbdool** [comment]
@kelizoliva I've got it working with a couple changes, such as with the way bulk updates will work. I started working on getting tests working but paused for now.

**Comment by ghost** [comment]
Very cool, we will test it out! Thanks!

**Comment by kelizoliva** [comment]
That ghost was me. We tested this out on a site and non-administrator users were unable to reset password or add users. 

We got the following error:

`Too few arguments to function role_delegation_user_presave(), 1 passed in /var/www/test/web/core/includes/module.inc on line 960 and exactly 2 expected`

**Comment by herbdool** [comment]
@kelizoliva I do not believe you were testing the right PR. It is this one: https://github.com/backdrop-contrib/role_delegation/pull/5/files

In the PR, `role_delegation_user_presave` accepts only argument, whereas the error you quoted has it accepting two. So please double check.

**Comment by herbdool** [comment]
I've updated the PR - fixed the tests so they are all passing. I also added `hook_user_role_delete` so that the test passes that checks for permission removed from other roles, when the role is deleted.

**Comment by herbdool** [comment]
@kelizoliva are you able to try this again?

**Comment by herbdool** [comment]
@kelizoliva will you have a chance to review? With my PR the module now fully works.

**Comment by kelizoliva** [comment]
@herbdool the project that we were attempting to apply this to is out of development, and I don't think we currently have any projects in development that this would apply to right now. I would be happy to test it in the future, but my plate is too full at the moment to passively test. I have this on my list to check when I have a chance though, thanks for your work!!

**Comment by herbdool** [comment]
@kelizoliva thanks for letting me know. If you prefer, an alternative is to allow me to be a maintainer as well and I can fix the bugs. Is that okay with you?

**Comment by olafgrabienski** [comment]
@herbdool I'm currently upgrading a D7 site with Role Delegation. After running `update.php` I wasn't able to proceed due to the module (see messages below). I've then applied your PR (the .module file part) and was able to continue, so thank you  very much!

I'm planning to report back if the module works as expected, will probably need time, though.

Messages after running update.php:

- Warning: Parameter 1 to role_delegation_user_presave() expected to be a reference, value given in module_invoke_all() (line 975 of core/includes/module.inc).
- ArgumentCountError: Too few arguments to function role_delegation_user_presave(), 1 passed in core/includes/module.inc on line 975 and exactly 2 expected in role_delegation_user_presave() (line 236 of modules/role_delegation-1.x-1.x/role_delegation.module).

**Comment by kelizoliva** [comment]
I should be able to review/test in late November early December.

**Comment by herbdool** [comment]
Hi @kelizoliva, do you have a sense if you'll be able to review this soon? Do you still want to be a maintainer of this module or interested in finding someone else to take over?

I've had to fork this module and apply my own fixes for our clients in the meanwhile.

**Comment by olafgrabienski** [comment]
@herbdool I've finally tested *Role Delegation* on the mentioned site, upgraded from D7, using the code from https://github.com/herbdool/role_delegation/archive/refs/heads/1.x-1.x.zip. Not tested thoroughly, but at first sight it works without issues:

- Enabled only certain "Assign role" permissions for Editors.
- Logged in as Editor. Was able to assign (only) the mentioned roles.
- Checked as admin on `admin/people`: Roles have been assigned.
- No errors or warnings.

**Comment by kelizoliva** [comment]
Hi Herb,

Apologies for how long it has taken me to get back to this. I tested the code from your pull request and everything looks good, I am merging that into master now!

**Comment by herbdool** [comment]
Thanks @kelizoliva
